title = "Vamadev BuildTech"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

# The site's parameters
[params]
  home = "Home"
  
  [menu]
    [[menu.header]]
      weight = 2
      name = "Service"
      url = "service"
    
    [[menu.header]]
      weight = 3
      name = "Projects"
      url = "project"
  
    [[menu.header]]
      weight = 4
      name = "Contact"
      url = "contact"

    [[menu.footer]]
      weight = 1
      name = "About us"
      url = "#"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "contact"
    [[menu.footer]]
      weight = 3
      name = "How it works"
      url = "project"

  [params.slider]
    enable = true
    title = "A Real Estate &amp; Contruction agency"
    subtitle = "We love construction and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"
    bgImage = "img/home-banner.jpg"
    btnText = "Discover Our Projects"
    url = "project"

  [params.wrapper]
    enable = true
    image = "img/elevation.jpg"
    title = "About Us"
    italic = "Virtuous At Work."
    paragraph = "Vamadev BuildTech private Limited is a regional level real estate consulting firm based out of Chennai. Our services are exclusive into Building Planning, Property Joint Venture business, Constructions, Contracting, Building."

  [params.blog]
    enable = false
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    bgImage = "img/features-bg.jpg"
    content = "At Vamadev BuildTech , We have initiated change to organise real estate and joint venture markets — Change Towards Quality Living. Our vision is to become a leading player in the field by proving quality service."
    [params.feature.button]
      caption = "View Projects"
      url = "project"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "We design delightful housing experiences."
    paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."
    #[params.call.button]
    #  url = "#"
    #  text = "reach out to us"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Stop by for a visit"
      address = "Plot no.145, Kundan Nagar, Kannivakam, Guduvancherry,Chennai - 600122"
      email = "Email: vamadevbuildtech@gmail.com"
      phone = "Phone: +91-9444571533, +91-9444371466"
    [params.contact.gmaps]
      title = "We Also Count in Google Maps"
      url = "https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15548.915611865928!2d80.1267024!3d13.0210902!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xdaaf45c5ecc3fe1c!2sVamadev%20BuildTech!5e0!3m2!1sen!2sin!4v1571630090803!5m2!1sen!2sin"
